### ISSUE TITLE
Integrate async i/o tests and validation into CI/CD pipeline

### ISSUE THREAD

**Issue by guenp** [microsoft/azure-quantum-python#174]
Currently, async I/O functionality is only tested in recording. We need to enable them for live tests, both the ones run in the azure-quantum-clients pipeline, but also the ones run in the [iqsharp Docker image](https://github.com/microsoft/iqsharp/tree/main/images/iqsharp-base).

We should also add a validation step to our CI/CD pipeline that tests for any changes to the code that need to be propagated to the async package.

**Comment by xinyi-joffre** [comment]
Closing since we deprecated aio package integration.
