### ISSUE TITLE
QPE/VQE chemistry sample Molecule.ipnyb seems to have a few missing dependencies

### ISSUE THREAD

**Issue by martinquantum** [microsoft/azure-quantum-python#272]
Starting from a clean install of the qdk, there seemed a few packages missing in the sample https://github.com/microsoft/qdk-python/blob/main/examples/chemistry/Molecule.ipynb 

Specifically, I needed to install the following packages to get the notebook to run (thanks to @cgranade for assistance with figuring this out!):
`conda install -c conda-forge varname`
`pip install jupyter_jsmol`
`conda install -c conda-forge rdkit`
`conda install -c conda-forge networkx`
`conda install -c conda-forge basis_set_exchange` 

The issue might be that the dependencies might be missing from the conda package metadata (e.g., qdk.chemistry may have only been tested for pip usage).

**Comment by guenp** [comment]
These dependencies are included in the accompanying environment.yml file:
https://github.com/microsoft/qdk-python/blob/main/qdk/environment.yml

I believe this sample is intended to be moved to the https://github.com/microsoft/Quantum repo, @cgranade could you confirm this is possible given the above requirements?

**Comment by xinyi-joffre** [comment]
The qdk.chemistry package has been deprecated, and is no longer supported.
