### ISSUE TITLE
Tests for 1Qbit and Toshiba should use marks

### ISSUE THREAD

**Issue by anpaz** [microsoft/azure-quantum-python#393]
In general, we control what tests to run with custom marks; this allow us to decide at runtime what 3rd party providers tests should run.
1Qbit and Toshiba are not following this pattern, instead they are using their own environment variables to explicitly enable the tests. They should be migrated to the general marks schema.

**Comment by xinyi-joffre** [comment]
Closing since both 1QBit and Toshiba are now deprecated.
