### ISSUE TITLE
job.get_results fail with expired token

### ISSUE THREAD

**Issue by anpaz** [microsoft/azure-quantum-python#553]
When trying to fetch the results of a job obtained through workspace.list_jobs(), the call might fail due to the storage token being expired, for example, when getting the results from the last job:
```
all_jobs = aqua_workspace.list_jobs()
job = all_jobs[-1]
job.get_results()
```

The workaround is to explifictly fetch the job again from the service:
```
all_jobs = aqua_workspace.list_jobs()
job = all_jobs[-1]
job = aqua_workspace.get_job(job.id)

job.get_results()
```

Ideally, `get_results` should automatically does this for the user.

**Comment by kikomiss** [comment]
The fix is implemented and is going to be included in the next release of `azure-quantum` package.
